### ISSUE TITLE
Running npm install fails on macOS and current npm/node

### ISSUE THREAD

**Issue by nk9** [samid737/phaser3-plugin-pathbuilder#38]
I just did this:

```
$ git clone https://github.com/samid737/phaser3-plugin-pathbuilder.git
$ cd phaser3-plugin-pathbuilder
$ npm i
```

In addition to a raft of deprecation warnings, the install failed with this error:

```
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://darasami.info:4870/statuses/-/statuses-1.4.0.tgz failed, reason: connect ECONNREFUSED 5.196.27.68:4870
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
npm ERR!     at ClientRequest.emit (node:events:390:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at Socket.emit (node:events:402:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:164:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR!  FetchError: request to http://darasami.info:4870/statuses/-/statuses-1.4.0.tgz failed, reason: connect ECONNREFUSED 5.196.27.68:4870
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
npm ERR!     at ClientRequest.emit (node:events:390:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at Socket.emit (node:events:402:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:164:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '5.196.27.68',
npm ERR!   port: 4870,
npm ERR!   type: 'system'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nick/.npm/_logs/2021-12-16T16_44_36_400Z-debug-0.log
```

Seems to be about the statuses package. And this is interesting, too:

```
$ rg statuses *.json
package-lock.json
1621:            "statuses": ">= 1.5.0 < 2",
1649:        "statuses": {
1651:          "resolved": "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz",
3101:        "statuses": "~1.5.0",
3122:        "statuses": {
3124:          "resolved": "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz",
3307:        "statuses": "~1.5.0",
3311:        "statuses": {
3313:          "resolved": "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz",
4308:        "statuses": ">= 1.4.0 < 2"
6828:        "statuses": "~1.5.0"
6839:            "statuses": ">= 1.5.0 < 2",
6858:        "statuses": {
6860:          "resolved": "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz",
8115:    "statuses": {
8117:      "resolved": "http://darasami.info:4870/statuses/-/statuses-1.4.0.tgz",
```

Are there really supposed to be two resolved versions? I am definitely not an expert at NPM package lockfiles, so maybe this is expected.

```
$ npm --version
8.3.0
$ node --version
v17.2.0
$ sw_vers
ProductName:	macOS
ProductVersion:	11.6.2
BuildVersion:	20G314
```

**Comment by nk9** [comment]
Deleting `dist/` and `package-lock.json` and trying again did the trick. Still a heap of deprecation warnings, though.

**Comment by samid737** [comment]
Hi , thanks, I still need to look into this, but indeed your workaround seems to help.
